.PHONY: clean All

All:
	@echo "----------Building project:[ GLEngine - Release (Windows32) ]----------"
	@cd "/home/davis-dev/Documents/Programming/C++/CodingGithub/GLEngine" && "$(MAKE)" -f  "GLEngine.mk"
clean:
	@echo "----------Cleaning project:[ GLEngine - Release (Windows32) ]----------"
	@cd "/home/davis-dev/Documents/Programming/C++/CodingGithub/GLEngine" && "$(MAKE)" -f  "GLEngine.mk" clean
