.PHONY: clean All

All:
	@echo "----------Building project:[ Fear-Of-The-Dark - Debug ]----------"
	@"$(MAKE)" -f  "Fear-Of-The-Dark.mk"
clean:
	@echo "----------Cleaning project:[ Fear-Of-The-Dark - Debug ]----------"
	@"$(MAKE)" -f  "Fear-Of-The-Dark.mk" clean
