.PHONY: clean All

All:
	@echo "----------Building project:[ DataMakerFOTD - Debug ]----------"
	@cd "/home/davis-dev/Documents/Programming/C++/CodingGithub/Fear-Of-The-Dark/Tools/DataMakerFOTD/DataMakerFOTD" && "$(MAKE)" -f  "DataMakerFOTD.mk"
clean:
	@echo "----------Cleaning project:[ DataMakerFOTD - Debug ]----------"
	@cd "/home/davis-dev/Documents/Programming/C++/CodingGithub/Fear-Of-The-Dark/Tools/DataMakerFOTD/DataMakerFOTD" && "$(MAKE)" -f  "DataMakerFOTD.mk" clean
